### ISSUE TITLE
Add intermediate event templates for Kafka and RabbitMQ inbound connectors

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors-bundle#672]
**What should we do?**

Add intermediate catch event element templates for RabbitMQ and Kafka inbound connectors.

**Why should we do it?**

We already support intermediate catch event template for Webhook connector. There is no reason not to support this feature for RabbitMQ and Kafka.

**Tasks**

- [x] Add new element templates to the connectors-bundle repo
- [x] https://github.com/camunda/camunda-platform-docs/issues/2206
- [x] https://github.com/camunda/camunda-platform-docs/issues/2206
- [x] Remove feature flag https://github.com/camunda/web-modeler/pull/4936
